### ISSUE TITLE
monstart fails

### ISSUE THREAD

**Issue by denismcapple** [nethunteros/rpi3-kalimon#1]
Hi there,

Im getting the following when trying to to run monstart - Any ideas?

**root@kali:/usr/bin# monstart
wlan0: ERROR while getting interface flags: No such device
root@kali:/usr/bin#**

Thanks!

**Comment by denismcapple** [comment]
Actually, I am an idiot, that was working all long as confirmed by running iwconfig

I am finding that it doesnt seem to work 100% with airodump-ng - It has difficulty identifying the Channel

 CH  4 ][ Elapsed: 1 min ][ 2016-12-20 22:16 ][ **fixed channel wlan0: -1**

From reading about this online, it appears to be driver related. Any ideas?

**Comment by nethunteros** [comment]
Hi @denismcapple. I'm tweaking the build script hourly/daily.  First release worked but wifi couldn't connect to AP. 

Recent builds monitor mode would turn on and AP would connect but airmon-ng issues as you mentioned.  

It's a work in progress.  I'll update this issue when I have a working build (working AP connect and monitor mode).

**Comment by denismcapple** [comment]
Sounds great! thanks for the update!

**Comment by nethunteros** [comment]
I have uploaded a working release (working for me): https://github.com/nethunteros/rpi3-kalimon/releases

Let me know if it works for you also! Thanks!

**Comment by denismcapple** [comment]
Nice one! 

Is it possible to update the image which I am already using at the moment without redeploying the whole OS?

Cheers

**Comment by denismcapple** [comment]
It's working! Amazing job, thanks for your efforts.

**Comment by nethunteros** [comment]
I'll continue tweaking kernel and firmware builds and see if I get a better image. I will upload to release page if I do.  Glad it works for you!
