### ISSUE TITLE
suggestion: kalimon minimal image

### ISSUE THREAD

**Issue by vay3t** [nethunteros/rpi3-kalimon#10]
the interesting idea is create a minimal version of kalimon (for 4gb memories) without GUI. It is useful to create a minimal image for small size memories

**Comment by nethunteros** [comment]
Great suggestion.  Should be easy to implement.

**Comment by vay3t** [comment]
I would appreciate you uploading an ISO to download

**Comment by nethunteros** [comment]
https://github.com/nethunteros/rpi3-kalimon/issues/9#issuecomment-280896020
