### ISSUE TITLE
Aircrack-ng problem

### ISSUE THREAD

**Issue by ghost** [nethunteros/rpi3-kalimon#13]
Hi,
Im getting this error when using aircrack-ng, airodump-ng, etc. : "Couldn't determine current channel for wlan0, you should either force the operation with --ignore-negative-one or apply a kernel patch."
Is someone getting the same error?
I think it has something to do with nexmon patch.

**Comment by vay3t** [comment]
please write in ur terminal `cat /proc/version/`

**Comment by ghost** [comment]
Linux version 4.4.39-v7_Re4son-Kali-Pi-TFT+ (root@nh-buildb
x) (gcc version 4.8.3 20140106 (prerelease) (crosstool-NG l
naro-1.13.1-4.8-2014.01 - Linaro GCC 2013.11) ) #1 SMP Fri
ec 30 09:58:20 CST 2016

**Comment by ghost** [comment]
IF I use "airmon-ng check kill" then it kills 2 process, but still getting this error while using aireplay-ng (for deauth).

**Comment by ghost** [comment]
Any ideas?

**Comment by vay3t** [comment]
my kernel is `Linux kali 4.4.49-v7+ #1 SMP Wed Mar 1 18:24:01 CST 2017 armv7l GNU/Linux` I have no idea what the problem is. maybe @binkybear can help u

**Comment by vay3t** [comment]
I just saw your problem, that's the way it is. Has to do with the patch that is applied in the kernel. To fix the problem in aireplay-ng you have to add `--ignore-negative-one` in the command line. Sorry for the delay. I have been traveling and I arrived recently

**Comment by ghost** [comment]
It works, but im little afraid of performance of deauth.Anyway closing.
