### ISSUE TITLE
kalimon on raspberry pi zero w ?

### ISSUE THREAD

**Issue by grejh0t** [nethunteros/rpi3-kalimon#20]
Hey is it posible to port this so it works on on rpi z w ?

**Comment by vay3t** [comment]
https://github.com/offensive-security/kali-arm-build-scripts/blob/master/rpi0w-nexmon.sh
good luck!

**Comment by nethunteros** [comment]
@grejh0t - See @vay3t link.  The script above will build a working image (I tested).  It should hopefully have an official release one day.
