### ISSUE TITLE
automatic rezise && new release

### ISSUE THREAD

**Issue by vay3t** [nethunteros/rpi3-kalimon#21]
It would be interesting to expand memory on the first boot without doing these steps:
```
sudo mount /dev/mmcblk0p1 /boot
raspi-config
> Expand the filesystem
> Reboot
```

http://elinux.org/RPi_Resize_Flash_Partitions

I would also like to take advantage of saying, that it is time to have a new release, both minimal and full image

**Comment by nethunteros** [comment]
Hey!  I know we talk privately so just want to put it out there for anyone watching.  I'm moving the rpi3 and rpi0-w build script to an official offsec build:

https://github.com/offensive-security/kali-arm-build-scripts

This repo will stick around but more for testing.  I've looked at using raspbians expandfs and I will play around it with some more and see if we can incorporate into future builds.
